spring:
  profiles:
    active: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: false
      hibernate.temp.use_jdbc_metadata_defaults: false
  messages:
    basename: i18n/messages
  mvc:
    servlet:
      load-on-startup: 1

  data:
    rest:
      base-path: /api

library:
  storage-path: ${user.home}/library-storage